swiftmailer:
    url: '%env(MAILER_URL)%'
    spool: { type: 'memory' }
    transport : smtp
    host: localhost
    port: 1025
    auth_mode: login
    username:
    password:
    encryption: ssl
    stream_options:
        ssl:
            allow_self_signed: true
            verify_peer: false
            verify_peer_name: false
