vich_uploader:
    db_driver: orm

    mappings:
        property_image:
            uri_prefix: /uploads/recipes
            upload_destination: '%kernel.project_dir%/public/uploads/recipes'

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
