<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerV8xxvSz\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerV8xxvSz/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerV8xxvSz.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerV8xxvSz\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerV8xxvSz\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'V8xxvSz',
    'container.build_id' => 'd2f7ad4b',
    'container.build_time' => 1577700971,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerV8xxvSz');
