<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9uixx87\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9uixx87/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9uixx87.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9uixx87\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container9uixx87\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '9uixx87',
    'container.build_id' => '961b301b',
    'container.build_time' => 1578931918,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9uixx87');
