<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7mGNjWn\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7mGNjWn/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7mGNjWn.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container7mGNjWn\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container7mGNjWn\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '7mGNjWn',
    'container.build_id' => '9d95f0e6',
    'container.build_time' => 1579442023,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7mGNjWn');
